version: '3.7'

services: 
    postgresql:
        image: postgres:13
        #restart: always
        env_file:
            - ./postgresql/.env.dev
        volumes: 
            - postgresql-data:/var/lib/postgresql/data
    odoo:
        build: ./odoo
        #restart: always
        depends_on:
            - postgresql
        volumes: 
            - odoo-data:/var/lib/odoo/
            - ./odoo/extra-addons/:/mnt/extra-addons/
            #- ./odoo/odoo.conf:/etc/odoo/odoo.conf
            
        #ports:
        #    - 8069:8069
        env_file:
            - ./odoo/.env.dev
    nginx:
        build: ./nginx
        #restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/ssl/:/etc/ssl/nginx/
            - ./nginx/sites-enabled/:/etc/nginx/conf.d/
        links:
            - odoo
        #depends_on:
        #    - odoo14
volumes: 
    postgresql-data:
    odoo-data:
